import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.story': 'Our Story',
    'nav.contact': 'Contact',
    'nav.international': 'International Order',

    // Navbar controls
    'nav.theme.toggle': 'Toggle theme',
    'nav.mobileMenu.toggle': 'Toggle mobile menu',
    'nav.mode.dark': 'Dark Mode',
    'nav.mode.light': 'Light Mode',

    // Hero
    'hero.subtitle': 'Pure Sulawesi Honey',
    'hero.title': 'Nature\'s Golden Treasure',
    'hero.description': 'Discover the authentic taste of Sulawesi\'s finest honey, harvested from pristine forests by generations of beekeepers.',
    'hero.cta': 'Explore Products',
    'hero.learn': 'Our Story',
    'hero.title.a': 'Nature\'s',
    'hero.title.b': 'Golden',
    'hero.title.c': 'Treasure',
    'hero.paragraph1': 'Pure honey from Sulawesi\'s wild forests,',
    'hero.paragraph2': 'harvested with care by local beekeepers',
    'hero.paragraph3': 'and bottled fresh for your table.',
    'hero.stats.pure': 'Pure Honey',
    'hero.stats.years': 'Years',
    'hero.stats.customers': 'Customers',
    'hero.imageAlt': 'Honey background',

    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'Premium Honey Collection',
    'products.description': 'Each bottle contains pure, unprocessed honey harvested from the wild forests of Sulawesi.',
    'products.plastic.small': 'Plastic Bottle - Small',
    'products.plastic.medium': 'Plastic Bottle - Medium',
    'products.plastic.large': 'Plastic Bottle - Large',
    'products.glass.small': 'Glass Bottle - Small',
    'products.glass.medium': 'Glass Bottle - Medium',
    'products.glass.large': 'Glass Bottle - Large',
    'products.order': 'Order Now',
    'products.weight': 'Weight',
    'products.selection': 'Product Selection',
    'products.packaging.plastic': 'Plastic Bottle',
    'products.packaging.glass': 'Glass Bottle',
    'products.viewDetails': 'View Details',
    'product.details.description': 'Description',
    'product.details.benefits': 'Benefits',
    'product.details.usage': 'How to Use',
    'product.details.storage': 'Storage',
    'product.details.close': 'Close',
    'product.details.packaging': 'Packaging',
    'product.details.packaging.glass.title': 'Glass Bottle',
    'product.details.packaging.glass.text': 'Food-grade glass keeps the honey intact without altering its taste or aroma, is easy to clean and reuse, and looks premium on your shelf.',
    'product.details.packaging.plastic.title': 'Plastic Bottle',
    'product.details.packaging.plastic.text': 'Made of food-grade, BPA-free plastic — lightweight, leak-proof, practical for travel and daily use, while keeping the honey fresh.',
    'product.details.certifications': 'Certifications',
    'product.details.certifications.labtest': 'Lab Test',
    'product.details.certifications.text': 'Halal, NKV, HACCP, and laboratory-test documents are available on request.',
    'product.details.disclaimer': 'This information is for reference only and is not a substitute for medical advice. Consult your doctor if you have specific health conditions.',

    // About
    'about.title': 'About Lontara Honey',
    'about.subtitle': 'The King of Sulawesi Honey',
    'about.p1': 'Lontara Honey represents the pinnacle of Sulawesi\'s honey tradition. Born from the pristine forests of South Sulawesi, our honey carries the essence of biodiversity found nowhere else on Earth.',
    'about.p2': 'We work directly with local beekeepers who have perfected their craft over generations, ensuring every drop of honey maintains its natural purity and exceptional quality.',
    'about.p3': 'Our commitment to sustainability means we harvest responsibly, protecting both the bees and their natural habitat for future generations.',
    'about.quality': 'Premium Quality',
    'about.quality.desc': '100% pure, unprocessed honey',
    'about.sustainable': 'Sustainable',
    'about.sustainable.desc': 'Eco-friendly harvesting',
    'about.authentic': 'Authentic',
    'about.authentic.desc': 'Direct from Sulawesi forests',
    'about.imageAlt': 'About Lontara Honey',
    'about.beeAlt': 'Bee',

    // Story
    'story.title': 'Our Story',
    'story.subtitle': 'From Raja Madu Sulawesi to Lontara Honey',
    'story.chapter': 'Chapter',
    'story.chapter1.title': 'Humble Beginnings',
    'story.chapter1.text': 'Raja Madu Sulawesi started as a small local honey business with limited reach and only a few opportunities to join events. With simple tools and a strong work ethic, every drop of honey was harvested with care from the forests of Sulawesi.',
    'story.chapter2.title': 'Commitment to Quality',
    'story.chapter2.text': 'Over time, the team focused on improving product quality and strengthening the identity of the business. Better processing, cleaner packaging, and more structured management slowly built trust with customers and partners.',
    'story.chapter3.title': 'Lontara Honey is Born',
    'story.chapter3.text': 'From this journey, Lontara Honey was born  a new brand that represents a more modern, hygienic, and professional standard. Carrying the spirit of the Lontara script, the brand reflects our roots in Sulawesi while embracing today\'s expectations.',
    'story.chapter4.title': 'Growing with a Clear Vision',
    'story.chapter4.text': 'Today the company continues to grow under the name Lontara Honey, bringing quality honey from Sulawesi to consumers across Indonesia. Our vision is to keep expanding responsibly, while honoring nature and the communities that make this journey possible.',

    // Contact
    'contact.title': 'Contact & Order',
    'contact.subtitle': 'We are ready to help you with your honey orders',
    'contact.name': 'Your Name',
    'contact.phone': 'Phone Number',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.whatsapp': 'Chat on WhatsApp',
    'contact.address': 'South Sulawesi, Indonesia',
    'contact.phoneRequired': 'Phone number is required.',
    'contact.toast.wait.title': 'Please wait a moment',
    'contact.toast.wait.desc': 'You can send another message in a few seconds.',
    'contact.toast.redirect.title': 'Redirecting to WhatsApp',
    'contact.toast.redirect.desc': 'Your message is ready to send!',
    'contact.wa.message': 'Hello Lontara Honey! I would like to place an order or ask about your products.',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone / WhatsApp',
    'contact.info.email': 'Email',
    'contact.paragraph1': 'Reach out to us for product information and wholesale inquiries,',
    'contact.paragraph2': 'or direct orders of Lontara Honey.',
    'contact.namePlaceholder': 'Your Name..',
    'contact.messagePlaceholder': 'Your message...',
    'contact.countryCode.aria': 'Country code',
    'contact.map.title': 'Lontara Honey Location',
    'contact.map.error.title': 'Unable to load map',
    'contact.map.error.address': 'Jl. Pangkabinanga, Pangkabinanga, Pallangga, Gowa, Sulawesi Selatan 92161',

    // Order
    'order.title': 'Complete Your Order',
    'order.product': 'Product',
    'order.price': 'Price',
    'order.name': 'Full Name',
    'order.phone': 'Phone Number',
    'order.notes': 'Notes (optional)',
    'order.payment': 'Payment Method',
    'order.submit': 'Place Order via WhatsApp',
    'order.bank': 'Bank Transfer',
    'order.ewallet': 'E-Wallet',
    'order.cod': 'Cash on Delivery',
    'order.phoneRequired': 'Phone number is required.',
    'order.namePlaceholder': 'Your Name..',
    'order.notesPlaceholder': 'Any special requests...',
    'order.comingSoon': 'Coming soon',
    'order.countryCode.aria': 'Country code',
    'order.bank.name': 'Bank Mandiri',
    'order.bank.number': 'Account number:',
    'order.bank.holder': 'Account holder:',
    'order.bank.confirm': 'Please confirm your order with our team before making a transfer.',
    'order.address': 'Delivery Address',
    'order.addressPlaceholder': 'Street, district, city, postal code...',
    'order.addressMaps': 'Choose on Map',
    'order.map.title': 'Pick a Location on the Map',
    'order.map.hint': 'Search a place or shop name, then pick from the result list — the selected address is copied and filled in automatically, and the map moves to that exact spot.',
    'order.map.open': 'Open in Google Maps',
    'order.map.copy': 'Copy Address',
    'order.map.copied': 'Address copied!',
    'order.map.search': 'Search address or place...',
    'order.map.searchBtn': 'Search',
    'order.map.resolving': 'Searching... ',
    'order.map.noResult': 'No results found. Try another keyword, or type the street / area name.',
    'order.qris.expires': 'QRIS session expires in',
    'order.qris.scan': 'Scan this QR with your e-wallet or mobile banking app.',
    'order.qris.rules.title': 'Please read before paying',
    'order.qris.rules.intro': 'How to pay with QRIS:',
    'order.qris.rules.rule1': '1. Pay the exact amount with the QR code below.',
    'order.qris.rules.rule2': '2. After paying, upload 1 photo of your transfer proof.',
    'order.qris.rules.rule3': '3. Your order is processed after we check your proof.',
    'order.qris.rules.agree': 'I understand and agree.',
    'order.qris.rules.required': 'Please check "I understand and agree" first to see the QR code.',
    'order.qris.proofReminder': 'IMPORTANT: Upload 1 photo of your transfer proof, then confirm below. Our team verifies the proof manually before the order is processed.',
    'order.qris.proof.label': 'Transfer Proof Photo',
    'order.qris.proof.hint': 'Upload 1 photo of your payment proof (bank transfer / mobile banking / e-wallet receipt). Maximum 1 photo, up to 5 MB.',
    'order.qris.proof.upload': 'Upload Photo',
    'order.qris.proof.replace': 'Replace Photo',
    'order.qris.proof.required': 'Please upload the transfer proof photo before confirming.',
    'order.qris.proof.uploading': 'Uploading proof...',
    'order.qris.proof.uploadFailed': 'Failed to upload the proof. Please try again.',
    'order.qris.proof.noConfig': 'Proof upload service is not configured yet. Please contact the store admin.',
    'order.qris.proof.tooLarge': 'The photo is too large. Maximum size is 5 MB.',
    'order.qris.proof.invalid': 'The file must be an image (photo).',
    'order.qris.confirm': 'I have completed the payment — the transfer proof photo above is the proof I paid.',
    'order.qris.proofRequired': 'Please confirm that you have paid and uploaded the proof.',
    'order.qris.expired.title': 'QRIS session expired',
    'order.qris.expired.desc': 'The 10-minute session has ended and the payment data was reset. Please select QRIS again to start a new session.',
    'order.wa.address': 'Address:',
    'order.wa.qris.note': 'Payment proof:',
    'order.wa.qris.manual': '(attach the transfer proof photo in this chat)',
    'order.wa.title': '🍯 *NEW ORDER - LONTARA HONEY*\n\n',
    'order.wa.product': '*Product:*',
    'order.wa.weight': '*Weight:*',
    'order.wa.price': '*Price:*',
    'order.wa.customer': '*Customer Details:*',
    'order.wa.name': 'Name:',
    'order.wa.phone': 'Phone:',
    'order.wa.payment': 'Payment:',
    'order.wa.notes': 'Notes:',
    'order.wa.thanks': 'Thank you for ordering Lontara Honey! 🐝',

    // International
    'international.eyebrow': 'International orders',
    'international.title': 'From Sulawesi to your destination',
    'international.description': 'We support export enquiries and wholesale orders. Shipping arrangements, costs, customs duties, and delivery timelines are confirmed with each buyer based on the destination country.',
    'international.card1.title': 'Global logistics',
    'international.card1.text': 'DHL, FedEx, Attaba Express, Forwarder SBL, and ALFI Logistik.',
    'international.card2.title': 'Secure payment',
    'international.card2.text': 'Bank transfer is available after order confirmation. PayPal is coming soon.',
    'international.card3.title': 'Documentation',
    'international.card3.text': 'Halal, NKV, HACCP, and laboratory-test documents are available on request.',
    'international.card4.title': 'Return support',
    'international.card4.text': 'Report a damaged shipment within 7 days of delivery with an unboxing video. Resolution is handled with the exporter.',
    'international.footer': 'Contact us for a country-specific shipping quotation.',
    'international.details.view': 'View Details',
    'international.details.item': 'items',

    // Testimonials
    'testimonials.eyebrow': 'Testimonials',
    'testimonials.title': 'Happy Customers',
    'testimonials.subtitle': 'Join thousands of customers who have experienced the magic of Lontara Honey',
    'testimonials.imageAlt': 'Happy customers enjoying Lontara Honey',
    'testimonials.customers': "500+ Happy Customers",
    'testimonials.ratingFrom': 'From 500+ verified reviews',
    'testimonials.seeAll': 'See all 500+ reviews',
    'testimonials.allTitle': 'All Reviews',
    'testimonials.more': '...and {count} more verified reviews',

    // Footer
    'footer.tagline': 'Pure honey from the heart of Sulawesi',
    'footer.tagline1': 'Pure honey from the heart of',
    'footer.tagline2': 'Sulawesi',
    'footer.rights': 'All rights reserved',
    'footer.navigation': 'Navigation',
    'footer.quickLink': 'Quick Link',
    'footer.services': 'Services',
    'footer.faqs': 'FAQs',
    'footer.blog': 'Blog',
    'footer.blog.comingSoon': 'Blog coming soon!',
    'footer.booking': 'Booking',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.shipping': 'Shipping Policy',
    'footer.refund': 'Refund Policy',
    'footer.premiumSupply': 'Premium Honey Supply',
    'footer.wholesale': 'Wholesale',
    'footer.retail': 'Retail',
    'footer.support': 'Support',
    'footer.copyright': '© 2026 Lontara Honey. All Rights Reserved.',
    'footer.websiteBy': 'WEBSITE BY',
    'footer.wa.booking': 'I would like to book Lontara Honey products',
    'footer.wa.wholesale': 'I am interested in wholesale Lontara Honey products',
    'footer.logoAlt': 'Lontara Honey logo',
    'footer.honeyAlt': 'Lontara Honey',
    'footer.social.instagram': 'Instagram',
    'footer.social.tiktok': 'TikTok',
    'footer.social.youtube': 'YouTube',
    'footer.northmadAria': 'Northmad Instagram',

    // Intro
    'intro.welcome': 'Welcome to',
    'intro.tagline': 'The Golden Treasure of Sulawesi',

    // WhatsApp button
    'whatsapp.message': 'Hello! I\'m interested in Lontara Honey products.',
    'whatsapp.mute.aria': 'Mute backsound',
    'whatsapp.unmute.aria': 'Unmute backsound',
    'whatsapp.chat.aria': 'Chat on WhatsApp',

    // Verification gate
    'verify.eyebrow': 'Access Verification',
    'verify.title1': 'Make sure',
    'verify.title2': 'you are not a robot',
    'verify.description': 'Mr Sumbul / Northmad Sigma says, verify first before entering the Lontara Honey website.',
    'verify.checking': 'Checking verification...',
    'verify.enter': 'Enter Website',
    'verify.logoAlt': 'Lontara Honey',
    'verify.siteKeyMissing': 'Turnstile site key is not configured.',
    'verify.invalidJson': 'Server verification did not respond with valid JSON.',
    'verify.failed': 'Verification failed. Please try again.',
    'verify.widgetFailed': 'The verification widget failed to load. Please refresh the page.',
    'verify.expired': 'Verification expired. Please check again.',
    'verify.scriptFailed': 'Verification script failed to load. Check your internet connection, then refresh the page.',

    // Country names
    'country.indonesia': 'Indonesia',
    'country.malaysia': 'Malaysia',
    'country.singapore': 'Singapore',
    'country.thailand': 'Thailand',
    'country.philippines': 'Philippines',
    'country.vietnam': 'Vietnam',
    'country.brunei': 'Brunei',
    'country.cambodia': 'Cambodia',
    'country.laos': 'Laos',
    'country.myanmar': 'Myanmar',
    'country.australia': 'Australia',
    'country.japan': 'Japan',
    'country.southKorea': 'South Korea',
    'country.china': 'China',
    'country.hongKong': 'Hong Kong',
    'country.macau': 'Macau',
    'country.taiwan': 'Taiwan',
    'country.india': 'India',
    'country.pakistan': 'Pakistan',
    'country.bangladesh': 'Bangladesh',
    'country.newZealand': 'New Zealand',
    'country.qatar': 'Qatar',
    'country.saudiArabia': 'Saudi Arabia',
    'country.uae': 'United Arab Emirates',
    'country.germany': 'Germany',
    'country.france': 'France',
    'country.italy': 'Italy',
    'country.netherlands': 'Netherlands',
    'country.uk': 'United Kingdom',
    'country.us': 'United States',

    // Legal
    'legal.back': '← Back to Lontara Honey',
    'legal.lastUpdated': 'Last updated: ',
    'legal.notFound': 'Page not found.',
    'legal.footer': 'Lontara Honey · PT Lontara Jaya Nusantara · South Sulawesi, Indonesia',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.updated': '23 August 2026',
    'legal.privacy.s1.heading': 'Information we collect',
    'legal.privacy.s1.text': 'We collect the name, telephone number, country code, delivery address, and message you submit through our contact and order forms.',
    'legal.privacy.s2.heading': 'How we use it',
    'legal.privacy.s2.text': 'We use this information solely to respond to enquiries, prepare quotations, confirm orders, arrange shipping, and provide customer support.',
    'legal.privacy.s3.heading': 'Third parties',
    'legal.privacy.s3.text': 'Order messages are sent to WhatsApp. The website also uses Google Maps and flag images supplied by FlagCDN. Their privacy practices apply when you use those services.',
    'legal.privacy.s4.heading': 'Contact',
    'legal.privacy.s4.text': 'For privacy questions, contact lontarajayanusantara@gmail.com.',
    'legal.terms.title': 'Terms & Conditions',
    'legal.terms.updated': '23 August 2026',
    'legal.terms.s1.heading': 'Order confirmation',
    'legal.terms.s1.text': 'An order is accepted only after Lontara Honey confirms product availability, price, payment method, and shipping arrangement in writing.',
    'legal.terms.s2.heading': 'Product information',
    'legal.terms.s2.text': 'Product images are illustrative. Natural honey may vary in colour, aroma, and texture between batches.',
    'legal.terms.s3.heading': 'International orders',
    'legal.terms.s3.text': 'Shipping costs, customs duties, taxes, import permissions, and delivery timelines are agreed with the buyer for the destination country before payment.',
    'legal.shipping.title': 'Shipping Policy',
    'legal.shipping.updated': '23 August 2026',
    'legal.shipping.s1.heading': 'Shipping partners',
    'legal.shipping.s1.text': 'Available logistics partners include DHL, FedEx, Attaba Express, Forwarder SBL, and ALFI Logistik.',
    'legal.shipping.s2.heading': 'Quotation',
    'legal.shipping.s2.text': 'Shipping method, charges, transit time, insurance, customs handling, and destination eligibility depend on the buyer agreement and destination country.',
    'legal.shipping.s3.heading': 'Tracking',
    'legal.shipping.s3.text': 'A tracking number or shipment reference is provided when available from the selected logistics partner.',
    'legal.refund.title': 'Refund & Return Policy',
    'legal.refund.updated': '23 August 2026',
    'legal.refund.s1.heading': 'Damaged shipments',
    'legal.refund.s1.text': 'Report damaged or incorrect shipments within 7 days after delivery and include a clear unboxing video, product photos, and order details.',
    'legal.refund.s2.heading': 'Review',
    'legal.refund.s2.text': 'Each eligible claim is reviewed with the exporter and relevant logistics partner. Resolution may include replacement, partial refund, or refund as agreed in writing.',
    'legal.refund.s3.heading': 'Non-returnable items',
    'legal.refund.s3.text': 'Opened, consumed, incorrectly stored, or buyer-damaged products are not eligible for return unless required by applicable law.',
    'legal.faq.title': 'Frequently Asked Questions',
    'legal.faq.updated': '23 August 2026',
    'legal.faq.s1.heading': 'Do you ship internationally?',
    'legal.faq.s1.text': 'Yes. Contact us with your destination and order quantity for a shipping quotation.',
    'legal.faq.s2.heading': 'Which payment methods are available?',
    'legal.faq.s2.text': 'Bank Mandiri transfer and QRIS are currently available. PayPal is coming soon.',
    'legal.faq.s3.heading': 'Are certificates available?',
    'legal.faq.s3.text': 'Halal, NKV, HACCP, and laboratory-test documents are available on request.',
    'legal.faq.s4.heading': 'How do I make a wholesale enquiry?',
    'legal.faq.s4.text': 'Send your required quantity, destination country, and preferred shipping terms through WhatsApp or the contact form.',

    // NotFound
    'notFound.title': 'Oops! Page not found',
    'notFound.back': 'Return to Home',

    // SEO
    'seo.title': 'Lontara Honey | Pure Sulawesi Honey',
  },
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.products': 'Produk',
    'nav.about': 'Tentang Kami',
    'nav.story': 'Cerita Kami',
    'nav.contact': 'Kontak',
    'nav.international': 'Pesanan Internasional',

    // Navbar controls
    'nav.theme.toggle': 'Ubah tema',
    'nav.mobileMenu.toggle': 'Buka/tutup menu',
    'nav.mode.dark': 'Mode Gelap',
    'nav.mode.light': 'Mode Terang',

    // Hero
    'hero.subtitle': 'Madu Murni Sulawesi',
    'hero.title': 'Harta Emas dari Alam',
    'hero.description': 'Temukan cita rasa autentik madu terbaik Sulawesi, dipanen dari hutan perawan oleh para peternak lebah turun-temurun.',
    'hero.cta': 'Lihat Produk',
    'hero.learn': 'Cerita Kami',
    'hero.title.a': 'Harta',
    'hero.title.b': 'Emas',
    'hero.title.c': 'dari Alam',
    'hero.paragraph1': 'Madu murni dari hutan liar Sulawesi,',
    'hero.paragraph2': 'dipanen penuh hati oleh peternak lokal',
    'hero.paragraph3': 'dan dikemas segar untuk meja Anda.',
    'hero.stats.pure': 'Madu Murni',
    'hero.stats.years': 'Tahun',
    'hero.stats.customers': 'Pelanggan',
    'hero.imageAlt': 'Latar belakang madu',

    // Products
    'products.title': 'Produk Kami',
    'products.subtitle': 'Koleksi Madu Premium',
    'products.description': 'Setiap botol berisi madu murni tanpa proses, dipanen dari hutan liar Sulawesi.',
    'products.plastic.small': 'Botol Plastik - Kecil',
    'products.plastic.medium': 'Botol Plastik - Sedang',
    'products.plastic.large': 'Botol Plastik - Besar',
    'products.glass.small': 'Botol Kaca - Kecil',
    'products.glass.medium': 'Botol Kaca - Sedang',
    'products.glass.large': 'Botol Kaca - Besar',
    'products.order': 'Pesan Sekarang',
    'products.weight': 'Berat',
    'products.selection': 'Pilihan Produk',
    'products.packaging.plastic': 'Botol Plastik',
    'products.packaging.glass': 'Botol Kaca',
    'products.viewDetails': 'Lihat Detail',
    'product.details.description': 'Deskripsi',
    'product.details.benefits': 'Manfaat',
    'product.details.usage': 'Cara Penggunaan',
    'product.details.storage': 'Penyimpanan',
    'product.details.close': 'Tutup',
    'product.details.packaging': 'Kemasan',
    'product.details.packaging.glass.title': 'Botol Kaca',
    'product.details.packaging.glass.text': 'Kaca food-grade menjaga kemurnian madu tanpa mengubah rasa dan aromanya, mudah dibersihkan dan bisa dipakai ulang, serta tampil premium di rak Anda.',
    'product.details.packaging.plastic.title': 'Botol Plastik',
    'product.details.packaging.plastic.text': 'Terbuat dari plastik food-grade bebas BPA — ringan, anti tumpah, praktis untuk dibawa bepergian dan dipakai sehari-hari, sambil tetap menjaga kesegaran madu.',
    'product.details.certifications': 'Sertifikasi',
    'product.details.certifications.labtest': 'Uji Lab',
    'product.details.certifications.text': 'Dokumen Halal, NKV, HACCP, dan hasil uji lab tersedia berdasarkan permintaan.',
    'product.details.disclaimer': 'Informasi ini hanya sebagai referensi dan bukan pengganti saran medis. Konsultasikan dengan dokter jika Anda memiliki kondisi kesehatan tertentu.',

    // About
    'about.title': 'Tentang Lontara Honey',
    'about.subtitle': 'Raja Madu Sulawesi',
    'about.p1': 'Lontara Honey merupakan puncak tradisi madu Sulawesi. Lahir dari hutan perawan Sulawesi Selatan, madu kami membawa esensi keanekaragaman hayati yang tidak ditemukan di tempat lain di Bumi.',
    'about.p2': 'Kami bekerja langsung dengan peternak lebah lokal yang telah menyempurnakan keahlian mereka selama beberapa generasi, memastikan setiap tetes madu mempertahankan kemurnian alami dan kualitas luar biasa.',
    'about.p3': 'Komitmen kami terhadap keberlanjutan berarti kami memanen secara bertanggung jawab, melindungi lebah dan habitat alami mereka untuk generasi mendatang.',
    'about.quality': 'Kualitas Premium',
    'about.quality.desc': 'Madu 100% murni tanpa proses',
    'about.sustainable': 'Berkelanjutan',
    'about.sustainable.desc': 'Pemanenan ramah lingkungan',
    'about.authentic': 'Autentik',
    'about.authentic.desc': 'Langsung dari hutan Sulawesi',
    'about.imageAlt': 'Tentang Lontara Honey',
    'about.beeAlt': 'Lebah',

    // Story
    'story.title': 'Perjalanan Kami',
    'story.subtitle': 'Dari Raja Madu Sulawesi ke Lontara Honey',
    'story.chapter': 'Bab',
    'story.chapter1.title': 'Awal yang Sederhana',
    'story.chapter1.text': 'Raja Madu Sulawesi berawal sebagai usaha madu lokal kecil dengan jangkauan yang masih terbatas dan jarang mengikuti berbagai event. Dengan peralatan sederhana dan kerja keras, setiap tetes madu dipanen dengan hati-hati dari hutan Sulawesi.',
    'story.chapter2.title': 'Komitmen pada Kualitas',
    'story.chapter2.text': 'Seiring waktu, fokus perusahaan bergeser pada peningkatan kualitas produk dan penguatan identitas bisnis. Proses pengolahan yang lebih baik, kemasan yang lebih bersih, dan pengelolaan yang lebih rapi perlahan membangun kepercayaan pelanggan dan mitra.',
    'story.chapter3.title': 'Lahirnya Lontara Honey',
    'story.chapter3.text': 'Dari perjalanan tersebut lahirlah Lontara Honey  sebuah brand baru yang merepresentasikan standar yang lebih modern, higienis, dan profesional. Membawa semangat aksara Lontara, brand ini mencerminkan akar kami di Sulawesi sekaligus menjawab harapan masa kini.',
    'story.chapter4.title': 'Tumbuh dengan Visi Jelas',
    'story.chapter4.text': 'Kini perusahaan terus tumbuh dengan nama Lontara Honey, menghadirkan madu berkualitas dari Sulawesi kepada konsumen di seluruh Indonesia. Visi kami adalah berkembang secara bertanggung jawab, sambil menghormati alam dan komunitas yang mendukung perjalanan ini.',

    // Contact
    'contact.title': 'Kontak & Pemesanan',
    'contact.subtitle': 'Kami siap membantu kebutuhan madu Anda',
    'contact.name': 'Nama Anda',
    'contact.phone': 'Nomor Telepon',
    'contact.message': 'Pesan',
    'contact.send': 'Kirim Pesan',
    'contact.whatsapp': 'Chat di WhatsApp',
    'contact.address': 'Sulawesi Selatan, Indonesia',
    'contact.phoneRequired': 'Nomor telepon wajib diisi.',
    'contact.toast.wait.title': 'Mohon tunggu sebentar',
    'contact.toast.wait.desc': 'Anda dapat mengirim pesan lagi dalam beberapa detik.',
    'contact.toast.redirect.title': 'Mengarahkan ke WhatsApp',
    'contact.toast.redirect.desc': 'Pesan Anda siap dikirim!',
    'contact.wa.message': 'Halo Lontara Honey! Saya ingin memesan atau menanyakan informasi seputar produk.',
    'contact.info.address': 'Alamat',
    'contact.info.phone': 'Telepon / WhatsApp',
    'contact.info.email': 'Email',
    'contact.paragraph1': 'Hubungi kami untuk informasi produk, pemesanan langsung,',
    'contact.paragraph2': 'atau kerja sama distribusi Lontara Honey.',
    'contact.namePlaceholder': 'Nama lengkap..',
    'contact.messagePlaceholder': 'Pesan Anda...',
    'contact.countryCode.aria': 'Kode negara',
    'contact.map.title': 'Lokasi Lontara Honey',
    'contact.map.error.title': 'Map tidak dapat dimuat',
    'contact.map.error.address': 'Jl. Pangkabinanga, Pangkabinanga, Pallangga, Gowa, Sulawesi Selatan 92161',

    // Order
    'order.title': 'Selesaikan Pesanan Anda',
    'order.product': 'Produk',
    'order.price': 'Harga',
    'order.name': 'Nama Lengkap',
    'order.phone': 'Nomor Telepon',
    'order.notes': 'Catatan (opsional)',
    'order.payment': 'Metode Pembayaran',
    'order.submit': 'Pesan via WhatsApp',
    'order.bank': 'Transfer Bank',
    'order.ewallet': 'E-Wallet',
    'order.cod': 'Bayar di Tempat',
    'order.phoneRequired': 'Nomor telepon wajib diisi.',
    'order.namePlaceholder': 'Nama lengkap..',
    'order.notesPlaceholder': 'Ada permintaan khusus...',
    'order.comingSoon': 'Segera hadir',
    'order.countryCode.aria': 'Kode negara',
    'order.bank.name': 'Bank Mandiri',
    'order.bank.number': 'Nomor rekening:',
    'order.bank.holder': 'Pemilik rekening:',
    'order.bank.confirm': 'Silakan konfirmasi pesanan Anda dengan tim kami sebelum melakukan transfer.',
    'order.address': 'Alamat Pengiriman',
    'order.addressPlaceholder': 'Jalan, kecamatan, kota, kode pos...',
    'order.addressMaps': 'Pilih di Peta',
    'order.map.title': 'Pilih Lokasi di Peta',
    'order.map.hint': 'Cari nama tempat/toko, lalu pilih dari daftar hasil — alamatnya otomatis disalin & diisi ke kolom Alamat, dan peta ikut pindah ke lokasi yang dipilih.',
    'order.map.open': 'Buka di Google Maps',
    'order.map.copy': 'Salin Alamat',
    'order.map.copied': 'Alamat disalin!',
    'order.map.search': 'Cari alamat atau tempat...',
    'order.map.searchBtn': 'Cari',
    'order.map.resolving': 'Mencari... ',
    'order.map.noResult': 'Tidak ada hasil ditemukan. Coba kata kunci lain, atau ketik nama jalan / daerah.',
    'order.qris.expires': 'Sesi QRIS berakhir dalam',
    'order.qris.scan': 'Pindai QR ini dengan e-wallet atau m-banking Anda.',
    'order.qris.rules.title': 'Baca dulu sebelum bayar',
    'order.qris.rules.intro': 'Cara bayar pakai QRIS:',
    'order.qris.rules.rule1': '1. Bayar sesuai harga pakai kode QR di bawah.',
    'order.qris.rules.rule2': '2. Setelah bayar, upload 1 foto bukti transfer.',
    'order.qris.rules.rule3': '3. Pesanan diproses setelah bukti dicek.',
    'order.qris.rules.agree': 'Saya paham dan setuju.',
    'order.qris.rules.required': 'Silakan centang "Saya paham dan setuju" dulu untuk melihat kode QR.',
    'order.qris.proofReminder': 'PENTING: Unggah 1 foto bukti transfer lalu konfirmasi di bawah. Tim kami memverifikasi bukti secara manual sebelum pesanan diproses.',
    'order.qris.proof.label': 'Foto Bukti Transfer',
    'order.qris.proof.hint': 'Unggah 1 foto bukti transfer (pesan e-banking / m-banking / e-wallet / struk ATM). Maksimal 1 foto, hingga 5 MB.',
    'order.qris.proof.upload': 'Unggah Foto',
    'order.qris.proof.replace': 'Ganti Foto',
    'order.qris.proof.required': 'Silakan unggah foto bukti transfer terlebih dahulu sebelum mencentang.',
    'order.qris.proof.uploading': 'Mengunggah bukti...',
    'order.qris.proof.uploadFailed': 'Gagal mengunggah bukti. Silakan coba lagi.',
    'order.qris.proof.noConfig': 'Layanan unggah bukti belum dikonfigurasi. Silakan hubungi admin toko.',
    'order.qris.proof.tooLarge': 'Foto terlalu besar. Ukuran maksimal 5 MB.',
    'order.qris.proof.invalid': 'File harus berupa gambar (foto).',
    'order.qris.confirm': 'Saya sudah melakukan pembayaran — foto bukti transfer di atas adalah bukti pembayaran saya.',
    'order.qris.proofRequired': 'Silakan konfirmasi bahwa Anda sudah membayar dan mengunggah buktinya.',
    'order.qris.expired.title': 'Sesi QRIS berakhir',
    'order.qris.expired.desc': 'Sesi 10 menit telah habis dan data pembayaran direset. Silakan pilih QRIS lagi untuk memulai sesi baru.',
    'order.wa.address': 'Alamat:',
    'order.wa.qris.note': 'Bukti pembayaran:',
    'order.wa.qris.manual': '(lampirkan foto bukti transfer di chat ini)',
    'order.wa.title': '🍯 *PESANAN BARU - LONTARA HONEY*\n\n',
    'order.wa.product': '*Produk:*',
    'order.wa.weight': '*Berat:*',
    'order.wa.price': '*Harga:*',
    'order.wa.customer': '*Detail Pelanggan:*',
    'order.wa.name': 'Nama:',
    'order.wa.phone': 'Telepon:',
    'order.wa.payment': 'Pembayaran:',
    'order.wa.notes': 'Catatan:',
    'order.wa.thanks': 'Terima kasih telah memesan Lontara Honey! 🐝',

    // International
    'international.eyebrow': 'Pesanan Internasional',
    'international.title': 'Dari Sulawesi ke tujuan Anda',
    'international.description': 'Kami melayani pertanyaan ekspor dan pesanan grosir. Pengaturan pengiriman, biaya, bea masuk, dan estimasi waktu dikonfirmasi bersama setiap pembeli berdasarkan negara tujuan.',
    'international.card1.title': 'Logistik global',
    'international.card1.text': 'DHL, FedEx, Attaba Express, Forwarder SBL, dan ALFI Logistik.',
    'international.card2.title': 'Pembayaran aman',
    'international.card2.text': 'Transfer bank tersedia setelah pesanan dikonfirmasi. PayPal segera hadir.',
    'international.card3.title': 'Dokumentasi',
    'international.card3.text': 'Dokumen Halal, NKV, HACCP, dan hasil uji lab tersedia berdasarkan permintaan.',
    'international.card4.title': 'Dukungan retur',
    'international.card4.text': 'Laporkan kiriman rusak dalam 7 hari setelah diterima dengan video unboxing. Penyelesaian ditangani bersama eksportir.',
    'international.footer': 'Hubungi kami untuk penawaran pengiriman sesuai negara tujuan.',
    'international.details.view': 'Lihat Detail',
    'international.details.item': 'item',

    // Testimonials
    'testimonials.eyebrow': 'Testimoni',
    'testimonials.title': 'Pelanggan Bahagia',
    'testimonials.subtitle': 'Bergabung dengan ribuan pelanggan yang telah merasakan keajaiban madu Lontara',
    'testimonials.imageAlt': 'Pelanggan bahagia menikmati Lontara Honey',
    'testimonials.customers': '500+ Pelanggan Puas',
    'testimonials.ratingFrom': 'Dari 500+ ulasan terverifikasi',
    'testimonials.seeAll': 'Lihat semua 500+ ulasan',
    'testimonials.allTitle': 'Semua Ulasan',
    'testimonials.more': '…dan {count} ulasan terverifikasi lainnya',

    // Footer
    'footer.tagline': 'Madu murni dari jantung Sulawesi',
    'footer.tagline1': 'Madu murni dari jantung',
    'footer.tagline2': 'Sulawesi',
    'footer.rights': 'Hak cipta dilindungi',
    'footer.navigation': 'Navigasi',
    'footer.quickLink': 'Tautan Cepat',
    'footer.services': 'Layanan',
    'footer.faqs': 'FAQ',
    'footer.blog': 'Blog',
    'footer.blog.comingSoon': 'Blog segera hadir!',
    'footer.booking': 'Pemesanan',
    'footer.privacy': 'Kebijakan Privasi',
    'footer.terms': 'Syarat & Ketentuan',
    'footer.shipping': 'Kebijakan Pengiriman',
    'footer.refund': 'Kebijakan Pengembalian',
    'footer.premiumSupply': 'Pasokan Madu Premium',
    'footer.wholesale': 'Grosir',
    'footer.retail': 'Eceran',
    'footer.support': 'Dukungan',
    'footer.copyright': '© 2026 Lontara Honey. Semua Hak Dilindungi Undang-Undang.',
    'footer.websiteBy': 'WEBSITE OLEH',
    'footer.wa.booking': 'Saya ingin memesan produk Lontara Honey',
    'footer.wa.wholesale': 'Saya tertarik dengan produk grosir Lontara Honey',
    'footer.logoAlt': 'Logo Lontara Honey',
    'footer.honeyAlt': 'Lontara Honey',
    'footer.social.instagram': 'Instagram',
    'footer.social.tiktok': 'TikTok',
    'footer.social.youtube': 'YouTube',
    'footer.northmadAria': 'Instagram Northmad',

    // Intro
    'intro.welcome': 'Selamat datang di',
    'intro.tagline': 'Harta Emas Sulawesi',

    // WhatsApp button
    'whatsapp.message': 'Halo! Saya tertarik dengan produk Lontara Honey.',
    'whatsapp.mute.aria': 'Bisukan backsound',
    'whatsapp.unmute.aria': 'Nyalakan kembali backsound',
    'whatsapp.chat.aria': 'Chat di WhatsApp',

    // Verification gate
    'verify.eyebrow': 'Verifikasi Akses',
    'verify.title1': 'Pastikan kamu',
    'verify.title2': 'bukan robot',
    'verify.description': 'Kata Mr Sumbul / Northmad Sigma, verifikasi terlebih dahulu sebelum masuk ke website Lontara Honey.',
    'verify.checking': 'Memeriksa verifikasi...',
    'verify.enter': 'Masuk ke Website',
    'verify.logoAlt': 'Lontara Honey',
    'verify.siteKeyMissing': 'Turnstile site key belum dikonfigurasi.',
    'verify.invalidJson': 'Server verifikasi tidak mengirim JSON yang valid.',
    'verify.failed': 'Verifikasi gagal. Coba lagi.',
    'verify.widgetFailed': 'Widget verifikasi gagal dimuat. Coba refresh halaman.',
    'verify.expired': 'Verifikasi kedaluwarsa. Silakan centang ulang.',
    'verify.scriptFailed': 'Script verifikasi gagal dimuat. Periksa koneksi internet lalu refresh halaman.',

    // Country names
    'country.indonesia': 'Indonesia',
    'country.malaysia': 'Malaysia',
    'country.singapore': 'Singapura',
    'country.thailand': 'Thailand',
    'country.philippines': 'Filipina',
    'country.vietnam': 'Vietnam',
    'country.brunei': 'Brunei',
    'country.cambodia': 'Kamboja',
    'country.laos': 'Laos',
    'country.myanmar': 'Myanmar',
    'country.australia': 'Australia',
    'country.japan': 'Jepang',
    'country.southKorea': 'Korea Selatan',
    'country.china': 'China',
    'country.hongKong': 'Hong Kong',
    'country.macau': 'Makau',
    'country.taiwan': 'Taiwan',
    'country.india': 'India',
    'country.pakistan': 'Pakistan',
    'country.bangladesh': 'Bangladesh',
    'country.newZealand': 'Selandia Baru',
    'country.qatar': 'Qatar',
    'country.saudiArabia': 'Arab Saudi',
    'country.uae': 'Uni Emirat Arab',
    'country.germany': 'Jerman',
    'country.france': 'Prancis',
    'country.italy': 'Italia',
    'country.netherlands': 'Belanda',
    'country.uk': 'Inggris Raya',
    'country.us': 'Amerika Serikat',

    // Legal
    'legal.back': '← Kembali ke Lontara Honey',
    'legal.lastUpdated': 'Terakhir diperbarui: ',
    'legal.notFound': 'Halaman tidak ditemukan.',
    'legal.footer': 'Lontara Honey · PT Lontara Jaya Nusantara · Sulawesi Selatan, Indonesia',
    'legal.privacy.title': 'Kebijakan Privasi',
    'legal.privacy.updated': '23 Agustus 2026',
    'legal.privacy.s1.heading': 'Informasi yang Kami Kumpulkan',
    'legal.privacy.s1.text': 'Kami mengumpulkan nama, nomor telepon, kode negara, alamat pengiriman, dan pesan yang Anda kirim melalui formulir kontak dan pemesanan kami.',
    'legal.privacy.s2.heading': 'Cara Kami Menggunakannya',
    'legal.privacy.s2.text': 'Kami menggunakan informasi ini semata-mata untuk menanggapi pertanyaan, menyiapkan penawaran, mengonfirmasi pesanan, mengatur pengiriman, dan memberikan dukungan pelanggan.',
    'legal.privacy.s3.heading': 'Pihak Ketiga',
    'legal.privacy.s3.text': 'Pesan pemesanan dikirim ke WhatsApp. Situs web juga menggunakan Google Maps dan gambar bendera dari FlagCDN. Kebijakan privasi mereka berlaku saat Anda menggunakan layanan tersebut.',
    'legal.privacy.s4.heading': 'Kontak',
    'legal.privacy.s4.text': 'Untuk pertanyaan privasi, hubungi lontarajayanusantara@gmail.com.',
    'legal.terms.title': 'Syarat & Ketentuan',
    'legal.terms.updated': '23 Agustus 2026',
    'legal.terms.s1.heading': 'Konfirmasi Pesanan',
    'legal.terms.s1.text': 'Pesanan diterima hanya setelah Lontara Honey mengonfirmasi ketersediaan produk, harga, metode pembayaran, dan pengaturan pengiriman secara tertulis.',
    'legal.terms.s2.heading': 'Informasi Produk',
    'legal.terms.s2.text': 'Gambar produk bersifat ilustratif. Madu alami dapat bervariasi dalam warna, aroma, dan tekstur antar batch.',
    'legal.terms.s3.heading': 'Pesanan Internasional',
    'legal.terms.s3.text': 'Biaya pengiriman, bea cukai, pajak, izin impor, dan estimasi waktu pengiriman disepakati dengan pembeli sesuai negara tujuan sebelum pembayaran.',
    'legal.shipping.title': 'Kebijakan Pengiriman',
    'legal.shipping.updated': '23 Agustus 2026',
    'legal.shipping.s1.heading': 'Mitra Pengiriman',
    'legal.shipping.s1.text': 'Mitra logistik yang tersedia meliputi DHL, FedEx, Attaba Express, Forwarder SBL, dan ALFI Logistik.',
    'legal.shipping.s2.heading': 'Penawaran',
    'legal.shipping.s2.text': 'Metode pengiriman, biaya, waktu pengiriman, asuransi, penanganan bea cukai, dan kelayakan tujuan bergantung pada kesepakatan pembeli dan negara tujuan.',
    'legal.shipping.s3.heading': 'Pelacakan',
    'legal.shipping.s3.text': 'Nomor pelacakan atau referensi pengiriman diberikan jika tersedia dari mitra logistik terpilih.',
    'legal.refund.title': 'Kebijakan Pengembalian & Refund',
    'legal.refund.updated': '23 Agustus 2026',
    'legal.refund.s1.heading': 'Kiriman Rusak',
    'legal.refund.s1.text': 'Laporkan kiriman yang rusak atau salah dalam 7 hari setelah diterima dan sertakan video unboxing yang jelas, foto produk, serta detail pesanan.',
    'legal.refund.s2.heading': 'Peninjauan',
    'legal.refund.s2.text': 'Setiap klaim yang memenuhi syarat ditinjau bersama eksportir dan mitra logistik terkait. Penyelesaian dapat berupa penggantian, pengembalian sebagian, atau pengembalian dana sesuai kesepakatan tertulis.',
    'legal.refund.s3.heading': 'Barang yang Tidak Dapat Dikembalikan',
    'legal.refund.s3.text': 'Produk yang sudah dibuka, dikonsumsi, disimpan dengan tidak benar, atau rusak oleh pembeli tidak memenuhi syarat pengembalian kecuali diwajibkan oleh hukum yang berlaku.',
    'legal.faq.title': 'Pertanyaan yang Sering Diajukan',
    'legal.faq.updated': '23 Agustus 2026',
    'legal.faq.s1.heading': 'Apakah Anda mengirim ke luar negeri?',
    'legal.faq.s1.text': 'Ya. Hubungi kami dengan tujuan dan jumlah pesanan Anda untuk mendapatkan penawaran pengiriman.',
    'legal.faq.s2.heading': 'Metode pembayaran apa saja yang tersedia?',
    'legal.faq.s2.text': 'Transfer Bank Mandiri dan QRIS saat ini tersedia. PayPal segera hadir.',
    'legal.faq.s3.heading': 'Apakah sertifikat tersedia?',
    'legal.faq.s3.text': 'Dokumen Halal, NKV, HACCP, dan hasil uji lab tersedia berdasarkan permintaan.',
    'legal.faq.s4.heading': 'Bagaimana cara mengajukan pertanyaan grosir?',
    'legal.faq.s4.text': 'Kirimkan jumlah yang dibutuhkan, negara tujuan, dan ketentuan pengiriman yang diinginkan melalui WhatsApp atau formulir kontak.',

    // NotFound
    'notFound.title': 'Ups! Halaman tidak ditemukan',
    'notFound.back': 'Kembali ke Beranda',

    // SEO
    'seo.title': 'Lontara Honey | Madu Murni Sulawesi',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getInitialLanguage = (): Language => 'en';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.setAttribute('translate', 'no');
    document.documentElement.classList.add('notranslate');
    document.title = translations[language]['seo.title'];
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};